/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libinverso_JavaInverso */

#ifndef _Included_libinverso_JavaInverso
#define _Included_libinverso_JavaInverso
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libinverso_JavaInverso
 * Method:    inverso
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_libinverso_JavaInverso_inverso
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
